/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#005049",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#86f2e4",
        "outline-variant": "#c6c6cd",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#008ebf",
        "on-secondary-fixed": "#00201d",
        "primary-fixed-dim": "#bec6e0",
        "outline": "#76777d",
        "on-background": "#191c1e",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#6bd8cb",
        "surface": "#f7f9fb",
        "secondary": "#006a61",
        "on-secondary-container": "#006f66",
        "inverse-surface": "#2d3133",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#001e2c",
        "inverse-primary": "#bec6e0",
        "tertiary-container": "#001e2c",
        "on-surface-variant": "#45464d",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "tertiary": "#000000",
        "tertiary-fixed": "#c4e7ff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#004c69",
        "surface-container-high": "#e6e8ea",
        "surface-dim": "#d8dadc",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#131b2e",
        "on-primary-container": "#7c839b",
        "surface-tint": "#565e74",
        "primary-container": "#131b2e",
        "secondary-fixed": "#89f5e7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1200px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
  ],
}
